package main

var KeyOptionName = [54]string{
	"Flip Position",
	"Flip Timeout",
	"Auto-Tune",
	"Message Indicator",
	"Reminder Notice",
	"Parental Code",
	"Purchase Code",
	"Power Loss Lock",
	"Time Display",
	"AC Output",
	"RF Bypass",
	"Volume",
	"Mute",
	"Dolby Digital",
	"Audio Output",
	"Stereo Output",
	"Compression",
	"Horizontal Screen Offset",
	"Vertical Screen Offset",
	"Text Language",
	"Hide Titles",
	"Bypass Locks",
	"Audio Language",
	"Guide Color",
	"Grid Cell Height",
	"Percent Disk Usage",
	"Amount of listings stored",
	"Subtitles",
	"Subtitle Language",
	"Subtitle Background",
	"Screen Saver",
	"Screen Saver Activation",
	"Mini-Guide Grid Cell Height",
	"Clear Locks",
	"Display Configuration",
	"About Us",
	"Descriptive Video Serv.",
	"Live Program Notice",
	"DVR Clipping",
	"Clickstream Opt-out",
	"DVR Folders",
	"DVR Overshoot",
	"Closed Captioning",
	"Captioning Background",
	"Favorite List 1",
	"Favorite List 2",
	"Favorite List 3",
	"Favorite List 4",
	"Favorite List 5",
}

func lookUpOptionKeyName(index int) string {
	return KeyOptionName[index-1]
}
